# Table of Contents
 <p><div class="lev1"><a href="#Task-1.-Compiling-Ebola-Data"><span class="toc-item-num">Task 1.&nbsp;&nbsp;</span>Compiling Ebola Data</a></div>
 <div class="lev1"><a href="#Task-2.-RNA-Sequences"><span class="toc-item-num">Task 2.&nbsp;&nbsp;</span>RNA Sequences</a></div>
 <div class="lev1"><a href="#Task-3.-Class-War-in-Titanic"><span class="toc-item-num">Task 3.&nbsp;&nbsp;</span>Class War in Titanic</a></div></p>

In [1]:
DATA_FOLDER = '../Data/' # Use the data folder provided in Tutorial 02 - Intro to Pandas.

## Task 1. Compiling Ebola Data

The `DATA_FOLDER/ebola` folder contains summarized reports of Ebola cases from three countries (Guinea, Liberia and Sierra Leone) during the recent outbreak of the disease in West Africa. For each country, there are daily reports that contain various information about the outbreak in several cities in each country.

Use pandas to import these data files into a single `Dataframe`.
Using this `DataFrame`, calculate for *each country*, the *daily average per month* of *new cases* and *deaths*.
Make sure you handle all the different expressions for *new cases* and *deaths* that are used in the reports.

In [87]:
# Write your answer here
import glob 
import pandas as pd
from IPython.core.display import display
subFolders = ["guinea_data", "liberia_data", "sl_data"]
subFolders = ["guinea_data"]
mainFolder = DATA_FOLDER + '/ebola/' 
ebolaFolders = [mainFolder + x for x in subFolders]
# print(ebolaFolders)
path = ebolaFolders # use your path
allFiles = []
for folder in ebolaFolders:
    allFiles += glob.glob(folder + "/*.csv")
# print(allFiles)    
frame = pd.DataFrame()
list_ = []
# print(allFiles)
for file_ in allFiles:
    df = pd.read_csv(file_,index_col=None, header=0)
#     print(df.head())
    list_.append(df)
frame = pd.concat(list_)
# frame.head()


frameNonNan = frame[frame['Dalaba'].notnull()]
# frameNonNan.head()

descriptions = frame['Description'].unique
print(descriptions.values.tolist())
# print(frame.keys())
# print(frame[['Date', 'Description']])
# nullDate = frame[frame[['Date']].isnull()].copy()
# row = nullDate.iloc[0]
      

# files0 = glob.glob(ebolaFolders[2] + "/*.csv")
# frame2 = pd.DataFrame()
# list2_ = []
# keyList = []
# for file_ in files0:
#     df2 = pd.read_csv(file_, index_col=None, header=0)
#     list2_.append(df2)
#     if(keyList == []):
#         keyList = list(df2.keys())
#         print(keyList)
#     else:
#         keys = list(df2.keys())
#         for key in keys:
#             if(key not in keyList):
#                 print(key)
#                 keyList.append(key)
# frame2 = pd.concat(list2_)
# print(frame2.keys())

AttributeError: 'function' object has no attribute 'values'

## Task 2. RNA Sequences

In the `DATA_FOLDER/microbiome` subdirectory, there are 9 spreadsheets of microbiome data that was acquired from high-throughput RNA sequencing procedures, along with a 10<sup>th</sup> file that describes the content of each. 

Use pandas to import the first 9 spreadsheets into a single `DataFrame`.
Then, add the metadata information from the 10<sup>th</sup> spreadsheet as columns in the combined `DataFrame`.
Make sure that the final `DataFrame` has a unique index and all the `NaN` values have been replaced by the tag `unknown`.

In [31]:
# Write your answer here
import glob
import pandas as pd
path = './Data/microbiome/' # use your path
allFiles = []
allFiles = glob.glob(path + "/*.xls")
print(allFiles)
listDf = []
for file in allFiles:
    df = pd.read_excel(file,index_col=None, header=0)
    listDf.append(df)

# finalDF = pd.concat(listDf)
finalDF = pd.read_excel(allFiles[1], index_col = None, header=None)

['./Data/microbiome\\metadata.xls', './Data/microbiome\\MID1.xls', './Data/microbiome\\MID2.xls', './Data/microbiome\\MID3.xls', './Data/microbiome\\MID4.xls', './Data/microbiome\\MID5.xls', './Data/microbiome\\MID6.xls', './Data/microbiome\\MID7.xls', './Data/microbiome\\MID8.xls', './Data/microbiome\\MID9.xls']

In [32]:
finalDF.iloc[0:]

                                                     0     1
0    Archaea "Crenarchaeota" Thermoprotei Desulfuro...     7
1    Archaea "Crenarchaeota" Thermoprotei Desulfuro...     2
2    Archaea "Crenarchaeota" Thermoprotei Sulfoloba...     3
3    Archaea "Crenarchaeota" Thermoprotei Thermopro...     3
4    Archaea "Euryarchaeota" "Methanomicrobia" Meth...     7
5    Archaea "Euryarchaeota" "Methanomicrobia" Meth...     1
6    Archaea "Euryarchaeota" "Methanomicrobia" Meth...     1
7    Archaea "Euryarchaeota" Archaeoglobi Archaeogl...     1
8    Archaea "Euryarchaeota" Archaeoglobi Archaeogl...     1
9    Archaea "Euryarchaeota" Halobacteria Halobacte...     1
10   Archaea "Euryarchaeota" Halobacteria Halobacte...     4
11   Archaea "Euryarchaeota" Halobacteria Halobacte...     1
12   Archaea "Euryarchaeota" Halobacteria Halobacte...     2
13   Archaea "Euryarchaeota" Halobacteria Halobacte...     4
14   Archaea "Euryarchaeota" Methanococci Methanoco...     1
15   Archaea "Euryarchaeota" Methanopyri Methanopyr...    12
16   Archaea "Euryarchaeota" Thermoplasmata Thermop...     2
17   Bacteria "Actinobacteria" Actinobacteria Actin...     2
18   Bacteria "Actinobacteria" Actinobacteria Actin...     1
19   Bacteria "Actinobacteria" Actinobacteria Actin...     1
20   Bacteria "Actinobacteria" Actinobacteria Actin...     1
21   Bacteria "Actinobacteria" Actinobacteria Actin...     2
22   Bacteria "Actinobacteria" Actinobacteria Actin...    53
23   Bacteria "Actinobacteria" Actinobacteria Actin...     1
24   Bacteria "Actinobacteria" Actinobacteria Actin...     2
25   Bacteria "Actinobacteria" Actinobacteria Actin...     3
26   Bacteria "Actinobacteria" Actinobacteria Actin...     1
27   Bacteria "Actinobacteria" Actinobacteria Actin...    99
28   Bacteria "Actinobacteria" Actinobacteria Actin...    17
29   Bacteria "Actinobacteria" Actinobacteria Actin...     2
..                                                 ...   ...
242  Bacteria "Proteobacteria" Gammaproteobacteria ...     1
243  Bacteria "Proteobacteria" Gammaproteobacteria ...     1
244  Bacteria "Proteobacteria" Gammaproteobacteria ...    11
245  Bacteria "Proteobacteria" Gammaproteobacteria ...     9
246  Bacteria "Proteobacteria" Gammaproteobacteria ...     1
247  Bacteria "Proteobacteria" Gammaproteobacteria ...   396
248  Bacteria "Proteobacteria" Gammaproteobacteria ...   414
249  Bacteria "Proteobacteria" Gammaproteobacteria ...  3732
250  Bacteria "Proteobacteria" Gammaproteobacteria ...     4
251  Bacteria "Proteobacteria" Gammaproteobacteria ...    22
252  Bacteria "Proteobacteria" Gammaproteobacteria ...     1
253  Bacteria "Proteobacteria" Gammaproteobacteria ...     4
254  Bacteria "Proteobacteria" Gammaproteobacteria ...     5
255  Bacteria "Proteobacteria" Gammaproteobacteria ...     6
256  Bacteria "Proteobacteria" Gammaproteobacteria ...     1
257  Bacteria "Proteobacteria" Gammaproteobacteria ...     1
258  Bacteria "Proteobacteria" Gammaproteobacteria ...     2
259  Bacteria "Proteobacteria" Gammaproteobacteria ...     2
260  Bacteria "Spirochaetes" Spirochaetes Spirochae...     1
261  Bacteria "Synergistetes" Synergistia Synergist...     2
262  Bacteria "Synergistetes" Synergistia Synergist...     1
263  Bacteria "Synergistetes" Synergistia Synergist...     1
264  Bacteria "Tenericutes" Mollicutes Haloplasmata...     1
265  Bacteria "Thermodesulfobacteria" Thermodesulfo...     1
266  Bacteria "Thermotogae" Thermotogae Thermotogal...     7
267  Bacteria "Thermotogae" Thermotogae Thermotogal...     9
268  Bacteria "Verrucomicrobia" Opitutae Opitutales...     1
269  Bacteria Cyanobacteria Cyanobacteria  Chloropl...     2
270  Bacteria Cyanobacteria Cyanobacteria  Chloropl...    85
271  Bacteria Cyanobacteria Cyanobacteria  Chloropl...  1388

[272 rows x 2 columns]

In [8]:
df.head()

  BARCODE               GROUP  SAMPLE
0    MID1  EXTRACTION CONTROL     NaN
1    MID2               NEC 1  tissue
2    MID3           Control 1  tissue
3    MID4               NEC 2  tissue
4    MID5           Control 2  tissue

## Task 3. Class War in Titanic

Use pandas to import the data file `Data/titanic.xls`. It contains data on all the passengers that travelled on the Titanic.

In [ ]:
from IPython.core.display import HTML
HTML(filename=DATA_FOLDER+'/titanic.html')

For each of the following questions state clearly your assumptions and discuss your findings:
1. Describe the *type* and the *value range* of each attribute. Indicate and transform the attributes that can be `Categorical`. 
2. Plot histograms for the *travel class*, *embarkation port*, *sex* and *age* attributes. For the latter one, use *discrete decade intervals*. 
3. Calculate the proportion of passengers by *cabin floor*. Present your results in a *pie chart*.
4. For each *travel class*, calculate the proportion of the passengers that survived. Present your results in *pie charts*.
5. Calculate the proportion of the passengers that survived by *travel class* and *sex*. Present your results in *a single histogram*.
6. Create 2 equally populated *age categories* and calculate survival proportions by *age category*, *travel class* and *sex*. Present your results in a `DataFrame` with unique index.

In [ ]:
# Write your answer here