# Table of Contents
 <p><div class="lev1"><a href="#Task-1.-Compiling-Ebola-Data"><span class="toc-item-num">Task 1.&nbsp;&nbsp;</span>Compiling Ebola Data</a></div>
 <div class="lev1"><a href="#Task-2.-RNA-Sequences"><span class="toc-item-num">Task 2.&nbsp;&nbsp;</span>RNA Sequences</a></div>
 <div class="lev1"><a href="#Task-3.-Class-War-in-Titanic"><span class="toc-item-num">Task 3.&nbsp;&nbsp;</span>Class War in Titanic</a></div></p>

In [3]:
DATA_FOLDER = '../Data/' # Use the data folder provided in Tutorial 02 - Intro to Pandas.

## Task 2. RNA Sequences

In the `DATA_FOLDER/microbiome` subdirectory, there are 9 spreadsheets of microbiome data that was acquired from high-throughput RNA sequencing procedures, along with a 10<sup>th</sup> file that describes the content of each. 

Use pandas to import the first 9 spreadsheets into a single `DataFrame`.
Then, add the metadata information from the 10<sup>th</sup> spreadsheet as columns in the combined `DataFrame`.
Make sure that the final `DataFrame` has a unique index and all the `NaN` values have been replaced by the tag `unknown`.

In [16]:
# Write your answer here
import glob
import pandas as pd
path = DATA_FOLDER + 'microbiome/' # use your path
allFiles = []
allFiles = glob.glob(path + "/MID*.xls")
print(allFiles)
listDf = []
for file in allFiles:
#     Get file name to put as header
    fileName = file.split('\\')[-1]
    print(fileName)
    df = pd.read_excel(file,index_col=None, header=None)
    listDf.append(df)

finalDF = pd.concat(listDf)
# finalDF = pd.read_excel(allFiles[1], index_col = None, header=None)

['../Data/microbiome\\MID1.xls', '../Data/microbiome\\MID2.xls', '../Data/microbiome\\MID3.xls', '../Data/microbiome\\MID4.xls', '../Data/microbiome\\MID5.xls', '../Data/microbiome\\MID6.xls', '../Data/microbiome\\MID7.xls', '../Data/microbiome\\MID8.xls', '../Data/microbiome\\MID9.xls']
MID1.xls
MID2.xls
MID3.xls
MID4.xls
MID5.xls
MID6.xls
MID7.xls
MID8.xls
MID9.xls

In [14]:
finalDF.iloc[0:]

                                                     0     1
0    Archaea "Crenarchaeota" Thermoprotei Desulfuro...     7
1    Archaea "Crenarchaeota" Thermoprotei Desulfuro...     2
2    Archaea "Crenarchaeota" Thermoprotei Sulfoloba...     3
3    Archaea "Crenarchaeota" Thermoprotei Thermopro...     3
4    Archaea "Euryarchaeota" "Methanomicrobia" Meth...     7
5    Archaea "Euryarchaeota" "Methanomicrobia" Meth...     1
6    Archaea "Euryarchaeota" "Methanomicrobia" Meth...     1
7    Archaea "Euryarchaeota" Archaeoglobi Archaeogl...     1
8    Archaea "Euryarchaeota" Archaeoglobi Archaeogl...     1
9    Archaea "Euryarchaeota" Halobacteria Halobacte...     1
10   Archaea "Euryarchaeota" Halobacteria Halobacte...     4
11   Archaea "Euryarchaeota" Halobacteria Halobacte...     1
12   Archaea "Euryarchaeota" Halobacteria Halobacte...     2
13   Archaea "Euryarchaeota" Halobacteria Halobacte...     4
14   Archaea "Euryarchaeota" Methanococci Methanoco...     1
15   Archaea "Euryarchaeota" Methanopyri Methanopyr...    12
16   Archaea "Euryarchaeota" Thermoplasmata Thermop...     2
17   Bacteria "Actinobacteria" Actinobacteria Actin...     2
18   Bacteria "Actinobacteria" Actinobacteria Actin...     1
19   Bacteria "Actinobacteria" Actinobacteria Actin...     1
20   Bacteria "Actinobacteria" Actinobacteria Actin...     1
21   Bacteria "Actinobacteria" Actinobacteria Actin...     2
22   Bacteria "Actinobacteria" Actinobacteria Actin...    53
23   Bacteria "Actinobacteria" Actinobacteria Actin...     1
24   Bacteria "Actinobacteria" Actinobacteria Actin...     2
25   Bacteria "Actinobacteria" Actinobacteria Actin...     3
26   Bacteria "Actinobacteria" Actinobacteria Actin...     1
27   Bacteria "Actinobacteria" Actinobacteria Actin...    99
28   Bacteria "Actinobacteria" Actinobacteria Actin...    17
29   Bacteria "Actinobacteria" Actinobacteria Actin...     2
..                                                 ...   ...
251  Bacteria "Proteobacteria" Gammaproteobacteria ...    10
252  Bacteria "Proteobacteria" Gammaproteobacteria ...     1
253  Bacteria "Proteobacteria" Gammaproteobacteria ...     1
254  Bacteria "Proteobacteria" Gammaproteobacteria ...     1
255  Bacteria "Proteobacteria" Gammaproteobacteria ...    12
256  Bacteria "Proteobacteria" Gammaproteobacteria ...     4
257  Bacteria "Proteobacteria" Gammaproteobacteria ...   805
258  Bacteria "Proteobacteria" Gammaproteobacteria ...   862
259  Bacteria "Proteobacteria" Gammaproteobacteria ...    12
260  Bacteria "Proteobacteria" Gammaproteobacteria ...  3534
261  Bacteria "Proteobacteria" Gammaproteobacteria ...     4
262  Bacteria "Proteobacteria" Gammaproteobacteria ...     1
263  Bacteria "Proteobacteria" Gammaproteobacteria ...    25
264  Bacteria "Proteobacteria" Gammaproteobacteria ...     2
265  Bacteria "Proteobacteria" Gammaproteobacteria ...     3
266  Bacteria "Proteobacteria" Gammaproteobacteria ...     2
267  Bacteria "Proteobacteria" Gammaproteobacteria ...     1
268  Bacteria "Proteobacteria" Gammaproteobacteria ...     3
269  Bacteria "Proteobacteria" Gammaproteobacteria ...     2
270  Bacteria "Proteobacteria" Gammaproteobacteria ...     1
271  Bacteria "Synergistetes" Synergistia Synergist...     3
272  Bacteria "Tenericutes" Mollicutes Anaeroplasma...     1
273  Bacteria "Tenericutes" Mollicutes Haloplasmata...    11
274  Bacteria "Thermodesulfobacteria" Thermodesulfo...     1
275  Bacteria "Thermodesulfobacteria" Thermodesulfo...     1
276  Bacteria "Thermotogae" Thermotogae Thermotogal...    43
277  Bacteria "Thermotogae" Thermotogae Thermotogal...    16
278  Bacteria "Verrucomicrobia" Opitutae Opitutales...     1
279  Bacteria Cyanobacteria Cyanobacteria  Chloropl...     1
280  Bacteria Cyanobacteria Cyanobacteria  Chloropl...    10

[2396 rows x 2 columns]

In [8]:
df.head()

  BARCODE               GROUP  SAMPLE
0    MID1  EXTRACTION CONTROL     NaN
1    MID2               NEC 1  tissue
2    MID3           Control 1  tissue
3    MID4               NEC 2  tissue
4    MID5           Control 2  tissue

## Task 3. Class War in Titanic

Use pandas to import the data file `Data/titanic.xls`. It contains data on all the passengers that travelled on the Titanic.

In [ ]:
from IPython.core.display import HTML
HTML(filename=DATA_FOLDER+'/titanic.html')

For each of the following questions state clearly your assumptions and discuss your findings:
1. Describe the *type* and the *value range* of each attribute. Indicate and transform the attributes that can be `Categorical`. 
2. Plot histograms for the *travel class*, *embarkation port*, *sex* and *age* attributes. For the latter one, use *discrete decade intervals*. 
3. Calculate the proportion of passengers by *cabin floor*. Present your results in a *pie chart*.
4. For each *travel class*, calculate the proportion of the passengers that survived. Present your results in *pie charts*.
5. Calculate the proportion of the passengers that survived by *travel class* and *sex*. Present your results in *a single histogram*.
6. Create 2 equally populated *age categories* and calculate survival proportions by *age category*, *travel class* and *sex*. Present your results in a `DataFrame` with unique index.

In [ ]:
# Write your answer here