# Table of Contents
 <p><div class="lev1"><a href="#Task-1.-Compiling-Ebola-Data"><span class="toc-item-num">Task 1.&nbsp;&nbsp;</span>Compiling Ebola Data</a></div>
 <div class="lev1"><a href="#Task-2.-RNA-Sequences"><span class="toc-item-num">Task 2.&nbsp;&nbsp;</span>RNA Sequences</a></div>
 <div class="lev1"><a href="#Task-3.-Class-War-in-Titanic"><span class="toc-item-num">Task 3.&nbsp;&nbsp;</span>Class War in Titanic</a></div></p>

In [2]:
DATA_FOLDER = "C:\\Users\\pace\\Google Drive\\Documents\\EPFL\\MA3\\ada\\ADA2017-Tutorials\\02 - Intro to Pandas\\Data" # Use the data folder provided in Tutorial 02 - Intro to Pandas.

In [3]:
import pandas as pd

## Task 1. Compiling Ebola Data

The `DATA_FOLDER/ebola` folder contains summarized reports of Ebola cases from three countries (Guinea, Liberia and Sierra Leone) during the recent outbreak of the disease in West Africa. For each country, there are daily reports that contain various information about the outbreak in several cities in each country.

Use pandas to import these data files into a single `Dataframe`.
Using this `DataFrame`, calculate for *each country*, the *daily average per month* of *new cases* and *deaths*.
Make sure you handle all the different expressions for *new cases* and *deaths* that are used in the reports.

In [273]:
import os
# Fetching the files
all_dataframes=[]

for country_dir in os.listdir(DATA_FOLDER+"\\ebola"):
    pathname = os.path.join(DATA_FOLDER+"\\ebola", country_dir)
    # We look at each country folder
    if os.path.isdir(pathname):
        # we recover all the dataframe for a particular country
        for csv_file in os.listdir(pathname):
            abs_path=os.path.join(pathname,csv_file)
            df=pd.read_csv(abs_path,index_col=0,parse_dates=[0])
            df['Country']=[country_dir]*df.shape[0]
            all_dataframes.append(df)

In [274]:
all_dataframes[0]

,Description,Totals,Conakry,Gueckedou,Macenta,Dabola,Kissidougou,Dinguiraye,Telimele,Boffa,Kouroussa,Dubreka,Siguiri,Pita,Nzerekore,Country
Date,,,,,,,,,,,,,,,,
2014-08-04,New cases of suspects,5,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,New cases of probables,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,New cases of confirmed,4,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,Total new cases registered so far,9,6.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,Total cases of suspects,11,9.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,Total cases of probables,133,8.0,95.0,11.0,3.0,4.0,1.0,3.0,5.0,2.0,0.0,0.0,1.0,0.0,guinea_data
2014-08-04,Total cases of confirmed,351,78.0,188.0,28.0,1.0,2.0,0.0,23.0,18.0,2.0,0.0,6.0,1.0,4.0,guinea_data
2014-08-04,Cumulative (confirmed + probable + suspects),495,95.0,285.0,39.0,4.0,6.0,1.0,26.0,23.0,4.0,0.0,6.0,2.0,4.0,guinea_data
2014-08-04,New deaths registered today,2,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,New deaths registered today (confirmed),2,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,New deaths registered today (probables),0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,New deaths registered today (suspects),0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,Total deaths of suspects,2,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,Total deaths of probables,133,8.0,95.0,11.0,3.0,4.0,1.0,3.0,5.0,2.0,0.0,0.0,1.0,0.0,guinea_data
2014-08-04,Total deaths of confirmed,228,32.0,152.0,18.0,1.0,1.0,0.0,7.0,11.0,1.0,0.0,3.0,1.0,1.0,guinea_data
2014-08-04,Total deaths (confirmed + probables + suspects),363,42.0,247.0,29.0,4.0,5.0,1.0,10.0,16.0,3.0,0.0,3.0,2.0,1.0,guinea_data
2014-08-04,Total PEC center today,31,21.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,guinea_data
2014-08-04,Total PEC center today (confirmed),18,10.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,guinea_data
2014-08-04,Total PEC center today (probables),0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,Total PEC center today (suspects),13,11.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,Total of deaths in confirmed cases in CTE,138,20.0,95.0,10.0,0.0,1.0,0.0,5.0,6.0,0.0,0.0,2.0,0.0,0.0,guinea_data
2014-08-04,Total of cured in confirmed cases in CTE,89,34.0,30.0,8.0,0.0,1.0,0.0,9.0,7.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,Number of male confirmed cases,161,48.0,72.0,14.0,1.0,1.0,0.0,6.0,10.0,1.0,0.0,6.0,0.0,2.0,guinea_data
2014-08-04,Number of female confirmed cases,190,30.0,116.0,14.0,0.0,1.0,0.0,17.0,8.0,1.0,0.0,0.0,1.0,2.0,guinea_data
2014-08-04,Number of male probables cases,52,4.0,34.0,5.0,1.0,1.0,0.0,1.0,3.0,2.0,0.0,0.0,1.0,0.0,guinea_data
2014-08-04,Number of female probables cases,81,4.0,61.0,6.0,2.0,3.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,Number of male suspects cases,7,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,guinea_data
2014-08-04,Number of female suspects cases,6,4.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,Total number of male cases,220,57.0,106.0,19.0,2.0,2.0,0.0,7.0,13.0,3.0,0.0,8.0,1.0,2.0,guinea_data
2014-08-04,Total number of female cases,277,38.0,179.0,20.0,2.0,4.0,1.0,19.0,10.0,1.0,0.0,0.0,1.0,2.0,guinea_data
2014-08-04,Number of confirmed cases among health workers,21,16.0,3.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,guinea_data
2014-08-04,Number of deaths of confirmed cases among heal...,12,10.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,Number of probables cases among health workers,8,1.0,4.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,Number of deaths of probables cases among heal...,8,1.0,4.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,Number of suspects cases among health workers,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,guinea_data
2014-08-04,Number of death of confirmed cases among healt...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,guinea_data
2014-08-04,Total contacts registered from start date,6309,1592.0,3049.0,430.0,69.0,158.0,0.0,259.0,397.0,53.0,118.0,141.0,41.0,69.0,guinea_data
2014-08-04,Number of contacts to follow today,795,350.0,201.0,46.0,0.0,0.0,0.0,0.0,0.0,37.0,0.0,135.0,26.0,69.0,guinea_data
2014-08-04,Number of contacts out of track,5513,1242.0,2848.0,384.0,69.0,159.0,0.0,259.0,397.0,16.0,118.0,6.0,15.0,0.0,guinea_data
2014-08-04,Number of contacts followed yesterday,772,331.0,200.0,44.0,0.0,0.0,0.0,0.0,0.0,37.0,0.0,134.0,26.0,0.0,guinea_data
2014-08-04,Number of patients tested,785,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,guinea_data
2014-08-04,Number of samples collected,1235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,guinea_data

In [ ]:
df=pd.concat(all_dataframes)
# Get the month
df['Month']=df.index.month
# Concatenate all the dfs

In [298]:
new_df=df[df['Country']=='guinea_data'][['Month','Description','Totals']]
interesting_metrics_description=['Total new cases registered so far','New deaths registered']

# Change "new deaths registered today" of first day to "new deaths registered"
new_description=new_df['Description']
new_description[new_description=='New deaths registered today']='New deaths registered'
new_df['Description']=new_description

new_df['Date']=new_df.index
new_df=new_df.set_index(['Description'])
new_df=new_df.loc[interesting_metrics_description]
new_df=new_df.set_index([new_df.index,'Month','Date'])
new_df['Totals']=pd.to_numeric(new_df['Totals'])
new_df=new_df.sum(level=['Description','Month'])
new_df
# Check number of days

                                         Totals
Description                       Month
New deaths registered             8.0      17.0
                                  9.0      57.0
                                  10.0     15.0
Total new cases registered so far 8.0     129.0
                                  9.0     314.0
                                  10.0     34.0

In [323]:
new_df=df[df['Country']=='liberia_data']
new_df=new_df[['Variable','National','Month']]
days_per_months = new_df['Month']
new_df=new_df.set_index('Variable')
cases_df=new_df.loc[['New Case/s (Suspected)','New Case/s (Probable)','New case/s (confirmed)']]
cases_df=cases_df.dropna()
cases_df=cases_df.set_index('Month')
cases_df=cases_df.sum(level=0)

#days_per_months=days_per_months.value_counts()
days_per_months

2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
2014-06-16     6
              ..
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
2014-12-09    12
Name: Month, dtype: int32

In [ ]:

# Set the new index
#df_h=df.set_index(['Country','month','Description'])
print('    Description:\n',df['Description'].unique())
print('    variable:\n',df['variable'].unique())
print('    Variable:\n',df['Variable'].unique())
interesting_metrics_description=['Total new cases registered so far','New deaths registered today']
interesting_metrics_Variable=["New Case/s (Suspected)","New Case/s (Probable)","New case/s (confirmed)","Newly reported deaths"]
interesting_metrics_variable=['new_noncase','new_suspected','new_probable','new_confirmed','death_suspected','death_probable','death_confirmed']
# Set the new index
#df_h=df.set_index(['Country','month','Description'])
print('    Description:\n',df['Description'].unique())
print('    variable:\n',df['variable'].unique())
print('    Variable:\n',df['Variable'].unique())
interesting_metrics_description=['Total new cases registered so far','New deaths registered today']
interesting_metrics_Variable=["New Case/s (Suspected)","New Case/s (Probable)","New case/s (confirmed)","Newly reported deaths"]
interesting_metrics_variable=['new_noncase','new_suspected','new_probable','new_confirmed','death_suspected','death_probable','death_confirmed']

In [112]:


df=df[df['Description']=='New cases of suspects' or df['variable']]
df

                      Description Totals      Country  month
2014-08-04  New cases of suspects      5  guinea_data      8
2014-08-26  New cases of suspects     18  guinea_data      8
2014-08-27  New cases of suspects     12  guinea_data      8
2014-08-30  New cases of suspects     15  guinea_data      8
2014-08-31  New cases of suspects      9  guinea_data      8
2014-09-02  New cases of suspects     11  guinea_data      9
2014-09-04  New cases of suspects     13  guinea_data      9
2014-09-07  New cases of suspects      5  guinea_data      9
2014-09-08  New cases of suspects      5  guinea_data      9
2014-09-09  New cases of suspects      9  guinea_data      9
2014-09-11  New cases of suspects      9  guinea_data      9
2014-09-14  New cases of suspects      0  guinea_data      9
2014-09-16  New cases of suspects      4  guinea_data      9
2014-09-17  New cases of suspects      4  guinea_data      9
2014-09-19  New cases of suspects      3  guinea_data      9
2014-09-21  New cases of suspects      1  guinea_data      9
2014-09-22  New cases of suspects      5  guinea_data      9
2014-09-23  New cases of suspects      4  guinea_data      9
2014-09-24  New cases of suspects      8  guinea_data      9
2014-09-26  New cases of suspects      2  guinea_data      9
2014-09-30  New cases of suspects      4  guinea_data      9
2014-10-01  New cases of suspects     28  guinea_data     10

In [101]:
for country in df_h.index.get_level_values(0).unique():
    print(country)
    print(df_h.loc[country])

guinea_data
                                                      Totals
month Description
8     New cases of suspects                                5
      New cases of probables                               0
      New cases of confirmed                               4
      Total new cases registered so far                    9
      Total cases of suspects                             11
      Total cases of probables                           133
      Total cases of confirmed                           351
      Cumulative (confirmed + probable + suspects)       495
      New deaths registered today                          2
      New deaths registered today (confirmed)              2
      New deaths registered today (probables)              0
      New deaths registered today (suspects)               0
      Total deaths of suspects                             2
      Total deaths of probables                          133
      Total deaths of confirmed                          228
      Total deaths (confirmed + probables + suspects)    363
      Total PEC center today                              31
      Total PEC center today (confirmed)                  18
      Total PEC center today (probables)                   0
      Total PEC center today (suspects)                   13
      Total of deaths in confirmed cases in CTE          138
      Total of cured in confirmed cases in CTE            89
      Number of male confirmed cases                     161
      Number of female confirmed cases                   190
      Number of male probables cases                      52
      Number of female probables cases                    81
      Number of male suspects cases                        7
      Number of female suspects cases                      6
      Total number of male cases                         220
      Total number of female cases                       277
...                                                      ...
10    New cases of confirmed                               6
      Total new cases registered so far                   34
      Total cases of suspects                             45
      Total cases of probables                           177
      Total cases of confirmed                           977
      Cumulative (confirmed + probable + suspects)      1199
      Total suspected non-class cases                    974
      New deaths registered                               15
      Total deaths of suspects                             0
      Total deaths of probables                          177
      Total deaths of confirmed                          562
      Total deaths (confirmed + probables + suspects)    739
      Fatality rate for confirmed and probables          62%
      New cases of confirmed among health workers          2
      Total case of confirmed among health workers        69
      New deaths registered among health workers           0
      Total deaths registered among health workers        35
      New admits to CTE so far                            25
      Total number of hospitalized cases in CTE          114
      Total number of exits from CTE                      29
      Total number of admissions to CTE                 1576
      New contacts registered so far                       0
      Total contacts registered from start date        11772
      Number of contacts to follow today                2661
      Number of contacts followed today                 2595
      Number of contacts out of the track 21 days       9110
      Number of contacts lost to follow up                 1
      Number of samples collected today                   25
      Number of samples under test                         0
      Total samples tested                              2832

[714 rows x 1 columns]
liberia_data
                  Totals
month Description
6     NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
...                  ...
12    NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN

[3152 rows x 1 columns]
sl_data
                  Totals
month Description
8     NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
...                  ...
12    NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN
      NaN            NaN

[3262 rows x 1 columns]

## Task 2. RNA Sequences

In the `DATA_FOLDER/microbiome` subdirectory, there are 9 spreadsheets of microbiome data that was acquired from high-throughput RNA sequencing procedures, along with a 10<sup>th</sup> file that describes the content of each. 

Use pandas to import the first 9 spreadsheets into a single `DataFrame`.
Then, add the metadata information from the 10<sup>th</sup> spreadsheet as columns in the combined `DataFrame`.
Make sure that the final `DataFrame` has a unique index and all the `NaN` values have been replaced by the tag `unknown`.

In [ ]:
# Write your answer here

## Task 3. Class War in Titanic

Use pandas to import the data file `Data/titanic.xls`. It contains data on all the passengers that travelled on the Titanic.

In [ ]:
from IPython.core.display import HTML
HTML(filename=DATA_FOLDER+'/titanic.html')

For each of the following questions state clearly your assumptions and discuss your findings:
1. Describe the *type* and the *value range* of each attribute. Indicate and transform the attributes that can be `Categorical`. 
2. Plot histograms for the *travel class*, *embarkation port*, *sex* and *age* attributes. For the latter one, use *discrete decade intervals*. 
3. Calculate the proportion of passengers by *cabin floor*. Present your results in a *pie chart*.
4. For each *travel class*, calculate the proportion of the passengers that survived. Present your results in *pie charts*.
5. Calculate the proportion of the passengers that survived by *travel class* and *sex*. Present your results in *a single histogram*.
6. Create 2 equally populated *age categories* and calculate survival proportions by *age category*, *travel class* and *sex*. Present your results in a `DataFrame` with unique index.

In [ ]:
# Write your answer here